import { USER_INTEREST_CHIPS } from "./user-interests";

/** Emoji prefix for home-screen deck focus chips (maps interest keys). */
const BASE: Record<string, string> = {
  walking: "🚶",
  hikes: "🥾",
  coffee: "☕",
  dessert: "🍰",
  exploring: "🧭",
  bookstores: "📚",
  museums: "🏛️",
  movies: "🎬",
  theater: "🎭",
  "live-music": "🎵",
  concerts: "🎤",
  comedy: "😂",
  improv: "🎙️",
  karaoke: "🎶",
  dancing: "💃",
  trivia: "🧠",
  nightlife: "🌃",
  sports: "⚽",
  bowling: "🎳",
  arcade: "🎮",
  "farmers-markets": "🥬",
  rooftops: "🌆",
  "working out": "💪",
  beach: "🌊",
  journaling: "✍️",
  reading: "📖",
  "calling friends": "📞",
  "solo-recharge": "🔋",
  "cheap-hangouts": "💸",
  pickleball: "🏓",
  tennis: "🎾",
  basketball: "🏀",
  soccer: "⚽",
  football: "🏈",
  baseball: "⚾",
  volleyball: "🏐",
  swimming: "🏊",
  "rock-climbing": "🧗",
  bouldering: "🪨",
  surfing: "🏄",
  skating: "⛸️",
  skateboarding: "🛹",
  cycling: "🚴",
  running: "🏃",
  yoga: "🧘",
  pilates: "🤸",
  "martial-arts": "🥋",
  karate: "🥋",
  boxing: "🥊",
  bjj: "🤼",
  crossfit: "🏋️",
  golf: "⛳",
  frisbee: "🥏",
  "paddle-boarding": "🏄",
  brunch: "🍳",
  sushi: "🍣",
  tacos: "🌮",
  ramen: "🍜",
  bbq: "🍖",
  pizza: "🍕",
  "wine-bars": "🍷",
  "craft-beer": "🍺",
  "cocktail-bars": "🍸",
  speakeasies: "🥃",
  "food-trucks": "🚚",
  "night-markets": "🌃",
  "cooking-classes": "👩‍🍳",
  "tasting-menus": "🍽️",
  "art-galleries": "🖼️",
  "street-art": "🎨",
  photography: "📷",
  "film-festivals": "🎞️",
  "indie-films": "🎥",
  "poetry-slams": "📜",
  "open-mics": "🎤",
  "spoken-word": "🗣️",
  "cultural-festivals": "🎉",
  opera: "🎭",
  ballet: "🩰",
  "contemporary-dance": "💃",
  "game-nights": "🎲",
  "escape-rooms": "🔐",
  "axe-throwing": "🪓",
  "mini-golf": "⛳",
  "go-karts": "🏎️",
  "laser-tag": "🔫",
  "paint-and-sip": "🎨",
  "pottery-classes": "🏺",
  "dance-classes": "💃",
  "salsa-nights": "💃",
  "speed-dating": "💘",
  "bar-crawls": "🍻",
  "rooftop-parties": "🌇",
  "hiking-outdoors": "🥾",
  "beach-volleyball": "🏐",
  "tide-pools": "🦀",
  camping: "⛺",
  stargazing: "🌌",
  "sunrise-spots": "🌅",
  "sunset-spots": "🌇",
  "nature-walks": "🌿",
  "dog-parks": "🐕",
  "botanical-gardens": "🌺",
  kayaking: "🛶",
  snorkeling: "🤿",
  "cafes-to-work": "💻",
  "journaling-spots": "📓",
  "scenic-drives": "🛣️",
  "people-watching": "👀",
  "thrift-shopping": "🛍️",
  "vintage-markets": "👗",
  "record-stores": "💿",
  "puzzle-cafes": "🧩",
  "board-game-cafes": "🎲",
  spas: "💆",
  "sound-baths": "🎵",
  "language-exchange": "🌍",
  "coding-meetups": "💻",
  "networking-events": "🤝",
  "lectures-talks": "🎓",
  "trivia-pub-quiz": "❓",
  "science-events": "🔬",
  "astronomy-nights": "🔭",
};

const EXTRA: Record<string, string> = {};
for (const { key } of USER_INTEREST_CHIPS) {
  if (!BASE[key]) EXTRA[key] = "✨";
}

export const DECK_FOCUS_EMOJI: Record<string, string> = { ...BASE, ...EXTRA };
