/** Emoji prefix for home-screen deck focus chips (maps USER_INTEREST_CHIPS keys). */
export const DECK_FOCUS_EMOJI: Record<string, string> = {
  walking: "🚶",
  hikes: "🥾",
  coffee: "☕",
  dessert: "🍰",
  exploring: "🧭",
  bookstores: "📚",
  museums: "🏛️",
  movies: "🎬",
  theater: "🎭",
  "live-music": "🎵",
  concerts: "🎤",
  comedy: "😂",
  improv: "🎙️",
  karaoke: "🎶",
  dancing: "💃",
  trivia: "🧠",
  nightlife: "🌃",
  sports: "⚽",
  bowling: "🎳",
  arcade: "🎮",
  "farmers-markets": "🥬",
  rooftops: "🌆",
  "working out": "💪",
  beach: "🌊",
  journaling: "✍️",
  reading: "📖",
  "calling friends": "📞",
  "solo-recharge": "🔋",
  "cheap-hangouts": "💸",
};
