import type { PlaceSuggestion } from "./curated-places";

export const PERSONAL_PLACES: PlaceSuggestion[] = [
  {
    id: "personal-usc-village-dulce",
    title: "Go to Dulce at USC Village",
    subtitle: "Easy coffee or pastry reset",
    category: "short",
    durationMinutes: 30,
    interests: ["coffee", "dessert", "solo-recharge", "cheap-hangouts"],
    vibes: ["solo", "social", "date"],
    neighborhoods: ["usc", "university park", "vernon", "los angeles"],
    weatherFit: ["any"],
    timeFit: ["morning", "midday", "afternoon"],
    priceText: "$$",
    reservationNeeded: false,
    address: "USC Village, Los Angeles, CA",
    mapQuery: "Dulce USC Village Los Angeles",
    whyThisFits: "A familiar, low-friction place that already feels easy to say yes to.",
    tags: ["indoor", "calm", "favorite"],
    distanceTextByArea: {
      usc: "5–10 min away",
      "university park": "5–10 min away",
      vernon: "10–15 min away",
      "los angeles": "15–25 min away",
    },
  },
  {
    id: "personal-rose-garden",
    title: "Walk through the Rose Garden at Exposition Park",
    subtitle: "A genuinely good reset walk",
    category: "short",
    durationMinutes: 30,
    interests: ["walking", "solo-recharge", "cheap-hangouts", "exploring"],
    vibes: ["solo", "date", "social"],
    neighborhoods: ["usc", "university park", "vernon", "los angeles"],
    weatherFit: ["sunny", "any"],
    timeFit: ["morning", "midday", "afternoon", "evening"],
    priceText: "$",
    reservationNeeded: false,
    address: "701 State Dr, Los Angeles, CA",
    mapQuery: "Exposition Park Rose Garden Los Angeles",
    whyThisFits: "Close, pretty, and specific enough that it feels like a real plan.",
    tags: ["outdoor", "calm", "favorite"],
    distanceTextByArea: {
      usc: "10–15 min away",
      "university park": "10–15 min away",
      vernon: "15–20 min away",
      "los angeles": "20–30 min away",
    },
  },
  {
    id: "personal-usc-village-trader-joes",
    title: "Do a quick Trader Joe’s run at USC Village",
    subtitle: "Useful errand that gets you moving",
    category: "short",
    durationMinutes: 25,
    interests: ["cheap-hangouts", "solo-recharge", "walking"],
    vibes: ["solo"],
    neighborhoods: ["usc", "university park", "vernon", "los angeles"],
    weatherFit: ["any"],
    timeFit: ["morning", "midday", "afternoon", "evening"],
    priceText: "$",
    reservationNeeded: false,
    address: "3131 S Hoover St, Los Angeles, CA",
    mapQuery: "Trader Joe's USC Village",
    whyThisFits: "Useful enough to feel productive, easy enough to actually do.",
    tags: ["indoor", "favorite"],
    distanceTextByArea: {
      usc: "5–10 min away",
      "university park": "5–10 min away",
      vernon: "10–15 min away",
      "los angeles": "15–25 min away",
    },
  },
  {
    id: "personal-last-bookstore",
    title: "Browse The Last Bookstore",
    subtitle: "A better kind of wandering",
    category: "short",
    durationMinutes: 60,
    interests: ["bookstores", "solo-recharge", "exploring", "coffee"],
    vibes: ["solo", "date", "social"],
    neighborhoods: ["downtown", "usc", "los angeles", "vernon"],
    weatherFit: ["any"],
    timeFit: ["midday", "afternoon", "evening"],
    priceText: "$",
    reservationNeeded: false,
    address: "453 S Spring St, Los Angeles, CA",
    mapQuery: "The Last Bookstore Los Angeles",
    whyThisFits: "A place that already has enough atmosphere to carry the outing.",
    tags: ["indoor", "calm", "explore", "favorite"],
    distanceTextByArea: {
      usc: "15–25 min away",
      "university park": "15–25 min away",
      vernon: "15–25 min away",
      downtown: "5–10 min away",
      "los angeles": "15–25 min away",
    },
  },
  {
    id: "personal-echo-park-lake",
    title: "Go sit by Echo Park Lake",
    subtitle: "Low-cost outdoor reset",
    category: "short",
    durationMinutes: 45,
    interests: ["walking", "exploring", "solo-recharge", "cheap-hangouts"],
    vibes: ["solo", "social", "date"],
    neighborhoods: ["echo park", "silver lake", "los angeles"],
    weatherFit: ["sunny", "any"],
    timeFit: ["afternoon", "evening"],
    priceText: "$",
    reservationNeeded: false,
    address: "751 Echo Park Ave, Los Angeles, CA",
    mapQuery: "Echo Park Lake Los Angeles",
    whyThisFits: "One of those places where doing nothing still feels like doing something.",
    tags: ["outdoor", "calm", "favorite"],
    distanceTextByArea: {
      "echo park": "5–10 min away",
      "silver lake": "10–15 min away",
      usc: "20–30 min away",
      "los angeles": "20–30 min away",
    },
  },
];